name: CI/CD Deploy Databricks Apps

on:
  push:
    branches:
      - main

jobs:
  test_deploy_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run tests
        run: |
          PYTHONPATH=. pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Validate Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          echo "Validating the Databricks Asset Bundle"
          databricks bundle validate -t dev --var "host=${DATABRICKS_HOST}"

      - name: Deploy Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        run: |
          echo "Deploying the Databricks Asset Bundle"
          databricks bundle deploy -t dev --var "host=${DATABRICKS_HOST}"

      - name: Run all Databricks apps
        run: python run_all_apps.py
