name: CI/CD Deploy Databricks Apps

on:
  push:
    branches:
      - main

jobs:
  test_deploy_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Validate Databricks Bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID }}
        run: |
          databricks bundle validate --t dev

      - name: Deploy Databricks bundle
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          SQL_WAREHOUSE_ID: ${{ secrets.SQL_WAREHOUSE_ID }}
        run: |
          databricks bundle deploy --t dev

      - name: Run all Databricks apps
        run: python run_all_apps.py
